extends Node

#Enuns
enum Video { MONITOR, WINDOWS, RESOLUTION, ASPECT, DYNAMICRENDER, RENDERSCALE, FRAMERATE, MAXFRAME, VSYNC, GAMMACORRECTION, CONTRAST, BRIGHTNESS, SHADERS, EFFECTSQUALITY, COLORBLIND, REDUCESCREENSHAKE, UISCALE }
enum Audio {MASTER, MUSIC, SFX}
enum Language {}

var settings : Dictionary = {
}
